-- any sql that is to be pre-loaded before testsuite runs goes in here
-- statements must be a single line without returns
INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL, STATE, STREET, VERSION) VALUES (1, 'Nepean', 'CA', 'K2X 5A1', 'ON', '20 Pinetrail Cress', 1)
INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL, STATE, STREET, VERSION) VALUES (2, 'Carp', 'CA', 'K0A 1L0', 'ON', '185 Charlies Lane', 1)
INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL, STATE, STREET, VERSION) VALUES (3, 'Carp', 'CA', 'K0A 1L0', 'ON', '186 Charlies Lane', 1)

INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, SALARY, VERSION, ADDR_ID) VALUES (1, 'Mike', 'Norman', '80000', '1', 1)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, SALARY, VERSION, ADDR_ID) VALUES (2, 'Lei', 'Cao', '50000', '1', 2)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, SALARY, VERSION, ADDR_ID) VALUES (3, 'Chenxiao', 'Cui', '70000', '1', 3)

INSERT INTO PROJECT (ID, DESCRIPTION, NAME, VERSION) VALUES (1, 'CRUD', 'Assignment1', '1')
INSERT INTO PROJECT (ID, DESCRIPTION, NAME, VERSION) VALUES (2, 'Multithreading', 'Assignment2', '1')
INSERT INTO PROJECT (ID, DESCRIPTION, NAME, VERSION) VALUES (3, 'JPA', 'Assignment3', '1')

INSERT INTO EMP_PROJ (EMP_ID, PROJ_ID) VALUES (1,1)
INSERT INTO EMP_PROJ (EMP_ID, PROJ_ID) VALUES (1,2)
INSERT INTO EMP_PROJ (EMP_ID, PROJ_ID) VALUES (1,3)



